# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'There-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for There-iOS


  pod 'Alamofire', '~> 5.1'
  pod 'Kingfisher', '~> 7.0'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKUser'


  #for Mac M1
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphoneimulator*]"] = "arm64"
    end
  end

end
