# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'There-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for There-iOS

  pod 'SnapKit', '~> 5.6.0'
  pod 'Then', '~> 3.0.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'Alamofire', '~> 5.1'
  pod 'Kingfisher', '~> 7.0'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKUser'
end
